services:
  redis:
    image: redis:alpine
    ports:
      - 7157:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.9.15-alpine
    command: -js -DV -m 8222 -p 4222
    ports:
      - 4222:4222
    healthcheck:
      test: [ "CMD-SHELL", "printf 'GET /healthz?js-enabled-only=true HTTP/1.1\r\nHost: localhost:8222\r\n\r\n' | nc -w 1 localhost 8222 | tail -n 1 | grep -wq '{\"status\":\"ok\"}'" ]
      interval: 1s
      timeout: 5s
      retries: 5

  waiting-for-the-services-to-be-ready:
    image: hello-world
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
#      nats-box:
#        condition: service_healthy
volumes:
  redis-data:

