#!/usr/bin/env bash

set -eou pipefail

#go run workspace > /dev/null 2>&1 &
go run workspace &
go_pid=$!

# Group id of the process
#pgid=$(ps x -o  "%p %r %y %x %c " | grep $go_pid | awk '{print $2}')

while ! nc -z localhost "$PORT"; do
  echo "Waiting for server to start..."
  if ! kill -0 $go_pid 2>/dev/null; then
    echo -e "\e[1;31mServer failed to start\e[0m"
    exit 1
  fi
  sleep 0.3
done

go_test_exit_code=1

if ./gotest workspace/tests -count=1 -v ./...; then
  go_test_exit_code=0
fi
echo "Stopping server with id $go_pid"

pkill -TERM -P $go_pid

# Only if the output of go run workspace is not redirected to /dev/null
#sleep 1

if [[ $go_test_exit_code -eq 0 ]]; then
  echo -e "\e[1;32mTests passed\e[0m"
else
  echo -e "\e[1;31mTests failed\e[0m"
  exit 1
fi
